# Generated by Django 2.2 on 2020-05-14 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('Codigo', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=50)),
                ('Editorial', models.CharField(max_length=50)),
                ('Paginas', models.IntegerField()),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Ejem_Usua',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Ejemplar')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='Libro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Libro'),
        ),
    ]
