# Generated by Django 2.2 on 2020-05-14 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20200514_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplar',
            name='Usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Usuario'),
        ),
        migrations.DeleteModel(
            name='Ejem_Usua',
        ),
    ]
