# Generated by Django 2.2 on 2020-06-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20200514_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejemplar',
            name='Usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='Ejemplar',
            field=models.ManyToManyField(to='biblioteca.Ejemplar'),
        ),
    ]
