# Generated by Django 2.2 on 2020-06-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_auto_20200606_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplar',
            options={'verbose_name': 'Ejemplar', 'verbose_name_plural': 'Ejemplares'},
        ),
    ]
