# Generated by Django 2.2 on 2020-06-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_auto_20200606_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='Codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
