# Generated by Django 2.2 on 2020-06-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_auto_20200624_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='Codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
